Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: It must be a valid EC2 instance type.
Resources:
  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-05912b6333beaa478
      InstanceType: !Ref InstanceType
      KeyName: KP-EC2-Lambda
      SecurityGroups:
        - launch-wizard-2
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: CPU alarm for my instance
      AlarmActions:
      - Ref: "MyTopic1"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '90'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value:
          Ref: "MyInstance1"
  MyTopic1:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: MyTopic1
      Subscription: 
        - Endpoint: "xyz@xyz.com"
          Protocol: "email"
      TopicName: MyTopic1
